# Generated by Django 5.2.6 on 2025-10-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('duracion', models.CharField(default='60 minutos', max_length=50)),
                ('imagen', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
