# Generated by Django 5.2.7 on 2025-11-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercadopago', 'Mercado Pago')], default='efectivo', max_length=20)),
                ('categoria', models.CharField(choices=[('servicios', 'Servicios'), ('productos', 'Productos'), ('gastos', 'Gastos'), ('sueldos', 'Sueldos'), ('alquiler', 'Alquiler'), ('servicios_publicos', 'Servicios Públicos'), ('otros', 'Otros')], default='servicios', max_length=30)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
