# Generated by Django 5.2.7 on 2025-11-12 14:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('reservas', '0004_reserva_estado_pago_alter_reserva_comprobante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateField()),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('efectivo_contado', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo físicamente contado al cerrar', max_digits=10, null=True)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia entre saldo calculado y efectivo contado', max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='barbero',
            field=models.ForeignKey(blank=True, help_text='Barbero asociado al movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='comprobante',
            field=models.ImageField(blank=True, help_text='Comprobante del movimiento', null=True, upload_to='comprobantes_caja/'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='reserva',
            field=models.ForeignKey(blank=True, help_text='Reserva asociada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, help_text='Usuario que registró el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='categoria',
            field=models.CharField(choices=[('servicios', 'Servicios'), ('productos', 'Productos'), ('gastos', 'Gastos'), ('sueldos', 'Sueldos'), ('alquiler', 'Alquiler'), ('servicios_publicos', 'Servicios Públicos'), ('otros', 'Otros')], default='servicios', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientocaja',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['-fecha', '-hora'], name='caja_movimi_fecha_396846_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['tipo', 'categoria'], name='caja_movimi_tipo_643bb4_idx'),
        ),
        migrations.AddField(
            model_name='cierrecaja',
            name='usuario_cierre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL),
        ),
    ]
