# Generated by Django 5.2.7 on 2025-11-14 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_cierrecaja_remove_movimientocaja_created_at_and_more'),
    ]

    operations = [
    ]
