# Generated by Django 5.1.2 on 2025-10-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('company', models.CharField(blank=True, max_length=160, verbose_name='Empresa')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Teléfono')),
                ('notes', models.CharField(blank=True, max_length=240, verbose_name='Notas')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['active'], name='proveedores_active_764457_idx'), models.Index(fields=['name'], name='proveedores_name_79ffc7_idx')],
            },
        ),
    ]
