# Generated by Django 5.1.2 on 2025-10-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_active_764457_idx',
        ),
        migrations.RemoveIndex(
            model_name='proveedor',
            name='proveedores_name_79ffc7_idx',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('productos_cabello', 'Productos para el cabello')], default='productos_cabello', max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='company',
            field=models.CharField(blank=True, max_length=200, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono'),
        ),
    ]
