# Generated by Django 5.1.2 on 2025-10-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_remove_proveedor_proveedores_active_764457_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('productos_cabello', 'Productos para el cabello')], default='Selecciona el tipo proveedor', max_length=50, verbose_name='Tipo'),
        ),
    ]
