# Generated by Django 5.2.7 on 2025-10-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_proveedor_direccion_alter_proveedor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('productos_cabello', 'Productos para el cabello')], default='productos_cabello', max_length=50, verbose_name='Tipo'),
        ),
    ]
