# Generated by Django 5.2.7 on 2025-10-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('apellido_cliente', models.CharField(max_length=100, verbose_name='Apellido del cliente')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('fecha', models.DateField(verbose_name='Fecha de la cita')),
                ('horario', models.TimeField(verbose_name='Hora de la cita')),
                ('barbero_id', models.IntegerField(verbose_name='ID del barbero')),
                ('barbero_nombre', models.CharField(max_length=100, verbose_name='Nombre del barbero')),
                ('servicios', models.JSONField(help_text='Lista de servicios en formato JSON', verbose_name='Servicios contratados')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total del servicio')),
                ('seña', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Seña pagada (30%)')),
                ('duracion_total', models.IntegerField(verbose_name='Duración total en minutos')),
                ('comprobante', models.ImageField(upload_to='comprobantes/%Y/%m/%d/', verbose_name='Comprobante de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Verificación'), ('confirmada', 'Confirmada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la reserva')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del administrador')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
