# Generated by Django 5.2.7 on 2025-10-29 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='barbero_id',
        ),
        migrations.AddField(
            model_name='reserva',
            name='barbero',
            field=models.ForeignKey(blank=True, help_text='Usuario barbero asignado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_como_barbero', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='barbero_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del barbero'),
        ),
    ]
