# Generated by Django 5.2.7 on 2025-11-05 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_reserva_barbero_id_reserva_barbero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del último pago'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercadopago', 'Mercado Pago')], max_length=20, verbose_name='Método de pago del saldo'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='saldo_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado posteriormente en la barbería', max_digits=10, verbose_name='Saldo pagado en el local'),
        ),
    ]
