# Generated by Django 5.2.7 on 2025-11-12 05:34

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_reserva_fecha_pago_reserva_metodo_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estado_pago',
            field=models.CharField(choices=[('sin_pagar', 'Sin Pagar'), ('parcial', 'Pago Parcial'), ('pagado', 'Pagado')], default='sin_pagar', max_length=20, verbose_name='Estado del pago'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/%d/', verbose_name='Comprobante de pago'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='duracion_total',
            field=models.IntegerField(default=60, verbose_name='Duración total en minutos'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='saldo_pagado',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado posteriormente en la barbería', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Saldo pagado en el local'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='servicios',
            field=models.JSONField(default=list, help_text='Lista de servicios en formato JSON', verbose_name='Servicios contratados'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='seña',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Seña pagada (30%)'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total del servicio'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha', 'barbero'], name='reservas_re_fecha_9c6f76_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['email_cliente'], name='reservas_re_email_c_b373e7_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='reservas_re_estado_7c17e1_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado_pago'], name='reservas_re_estado__fac4b1_idx'),
        ),
    ]
